<?php

namespace AppBundle\Repository;

use AppBundle\Entity\About;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * AboutRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AboutRepository extends EntityRepository
{
    /**
     * @return Query
     */
    public function findAllQuery()
    {
        $qb = $this->createQueryBuilder('about');

        return $qb->getQuery();
    }

    /**
     * @param string $filter
     *
     * @return Query
     */
    public function findAllByFilter(string $filter)
    {
        $qb = $this->createQueryBuilder('about');

        return $qb->where(
            $qb->expr()->orX(
                $qb->expr()->like('about.id', ':value'),
                $qb->expr()->like('about.name', ':value'),
                $qb->expr()->like('about.amount', ':value')
            )
        )
            ->setParameter('value', "%" . trim($filter) . "%")
            ->getQuery();
    }

    /**
     * @param bool $value
     *
     * @return About[]|null
     */
    public function findAllByShowAbout(bool $value)
    {
        $qb = $this->createQueryBuilder('about');

        return $qb->where(
            $qb->expr()->eq('about.showAbout', ':value')
        )
            ->setParameter('value', $value)
            ->getQuery()
            ->getResult();
    }
}
