<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * InstallmentRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstallmentRepository extends EntityRepository
{
    /**
     * @return Query
     */
    public function findAllQuery(): Query
    {
        $qb = $this->createQueryBuilder('installment');

        return $qb->getQuery();
    }
}
