<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Installment;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * InstallmentRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstallmentRepository extends EntityRepository
{
    /**
     * @return Query
     */
    public function findAllQuery(): Query
    {
        $qb = $this->createQueryBuilder('installment');

        return $qb->getQuery();
    }

    /**
     * @param string $value
     *
     * @return Installment[]|null
     */
    public function findAllByState(
        string $value
    ): ?array {
        $qb = $this->createQueryBuilder('installment');

        return $qb->where(
            $qb->expr()->like('installment.state', ':value')
        )
            ->setParameter('value', $value)
            ->getQuery()
            ->getResult();
    }
}
