<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Plan;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * PlanRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanRepository extends EntityRepository
{
    /**
     * @return Query
     */
    public function findAllQuery()
    {
        $qb = $this->createQueryBuilder('plan');

        return $qb->getQuery();
    }

    /**
     * @param bool $value
     *
     * @return Plan[]|null
     */
    public function findAllByShowPlan(bool $value)
    {
        $qb = $this->createQueryBuilder('plan');

        return $qb->where(
            $qb->expr()->eq('plan.showPlan', ':value')
        )
            ->setParameter('value', $value)
            ->getQuery()
            ->getResult();
    }
}
