<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Student;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * ProgressHistoryRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgressHistoryRepository extends EntityRepository
{
    /**
     * @param Student $student
     *
     * @return Query
     */
    public function findAllByStudent(Student $student)
    {
        $qb = $this->createQueryBuilder('progressHistory');

        return $qb->where(
            $qb->expr()->eq('progressHistory.student', ':value')
        )
            ->setParameter('value', $student)
            ->getQuery();
    }
}
