<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Settings;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * SettingsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 */
class SettingsRepository extends EntityRepository
{
    /**
     * This constant represents a settings code in database
     */
    const SITE_NAME_CODE = 'site_name';

    /**
     * This constant represents a settings code in database
     */
    const CONTACT_LOCATION_CODE = 'contact_location';

    /**
     * This constant represents a settings code in database
     */
    const CONTACT_PHONE_CODE = 'contact_phone';

    /**
     * This constant represents a settings code in database
     */
    const CONTACT_EMAIL_CODE = 'contact_email';

    /**
     * This constant represents a settings code in database
     */
    const CONTACT_SCHEDULE_DAYS_CODE = 'contact_schedules_days';

    /**
     * This constant represents a settings code in database
     */
    const CONTACT_SCHEDULE_HOURS_CODE = 'contact_schedules_hours';

    /**
     * This constant represents a settings code in database
     */
    const CALENDAR_LAST_DAY_CODE = 'calendar_last_day';

    /**
     * @return Query
     */
    public function findAllQuery(): Query
    {
        $qb = $this->createQueryBuilder('settings');

        return $qb->getQuery();
    }

    /**
     * @param string $filter
     *
     * @return Query
     */
    public function findAllByFilter(string $filter): Query
    {
        $qb = $this->createQueryBuilder('settings');

        return $qb->where(
            $qb->expr()->orX(
                $qb->expr()->like('settings.id', ':value'),
                $qb->expr()->like('settings.name', ':value'),
                $qb->expr()->like('settings.value', ':value')
            )
        )
            ->setParameter('value', "%" . trim($filter) . "%")
            ->getQuery();
    }

    /**
     * @param string $code
     *
     * @return Settings|null
     */
    public function findOneByCode(string $code): ?Settings
    {
        $qb = $this->createQueryBuilder('settings');
        $qb->where($qb->expr()->eq('settings.code', ':code'))->setParameter(
            'code', $code
        );

        return $qb->getQuery()->getOneOrNullResult();
    }
}
