<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Doctrine\ORM\QueryBuilder;

/**
 * ShiftRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShiftRepository extends EntityRepository
{
    /**
     * @return Query
     */
    public function findAllQuery()
    {
        $qb = $this->createQueryBuilder('shift');

        return $qb->getQuery();
    }

    /**
     * @return QueryBuilder
     */
    public function findAllWithoutYear()
    {
        $qb = $this->createQueryBuilder('shift');

        return $qb->where(
            $qb->expr()->isNull('shift.year')
        );
    }
}
