# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
  AppBundle\DataFixtures\:
    resource: '../../src/AppBundle/DataFixtures'
    tags: [ 'doctrine.fixture.orm' ]