<?php

namespace AppBundle\DataFixtures\ORM;

use AppBundle\Entity\MedicalHistory;
use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\FixtureInterface;
use Doctrine\Persistence\ObjectManager;

/**
 * Class LoadMedicalHistoryData.
 *
 * @author David Bosio <dbosio@pagos360.com>
 */
class LoadMedicalHistoryData extends AbstractFixture implements FixtureInterface
{
    const MEDICAL_HISTORY_1 = "medical_history_1";
    const MEDICAL_HISTORY_2 = "medical_history_2";
    const MEDICAL_HISTORY_3 = "medical_history_3";
    const MEDICAL_HISTORY_4 = "medical_history_4";
    const MEDICAL_HISTORY_5 = "medical_history_5";
    const MEDICAL_HISTORY_6 = "medical_history_6";
    const MEDICAL_HISTORY_7 = "medical_history_7";
    const MEDICAL_HISTORY_8 = "medical_history_8";
    const MEDICAL_HISTORY_9 = "medical_history_9";
    const MEDICAL_HISTORY_10 = "medical_history_10";
    const MEDICAL_HISTORY_11 = "medical_history_11";
    const MEDICAL_HISTORY_12 = "medical_history_12";
    const MEDICAL_HISTORY_13 = "medical_history_13";
    const MEDICAL_HISTORY_14 = "medical_history_14";
    const MEDICAL_HISTORY_15 = "medical_history_15";
    const MEDICAL_HISTORY_16 = "medical_history_16";
    const MEDICAL_HISTORY_17 = "medical_history_17";
    const MEDICAL_HISTORY_18 = "medical_history_18";
    const MEDICAL_HISTORY_19 = "medical_history_19";
    const MEDICAL_HISTORY_20 = "medical_history_20";
    const MEDICAL_HISTORY_21 = "medical_history_21";
    const MEDICAL_HISTORY_22 = "medical_history_22";
    const MEDICAL_HISTORY_23 = "medical_history_23";
    const MEDICAL_HISTORY_24 = "medical_history_24";
    const MEDICAL_HISTORY_25 = "medical_history_25";
    const MEDICAL_HISTORY_26 = "medical_history_26";
    const MEDICAL_HISTORY_27 = "medical_history_27";
    const MEDICAL_HISTORY_28 = "medical_history_28";
    const MEDICAL_HISTORY_29 = "medical_history_29";
    const MEDICAL_HISTORY_30 = "medical_history_30";
    const MEDICAL_HISTORY_31 = "medical_history_31";
    const MEDICAL_HISTORY_32 = "medical_history_32";
    const MEDICAL_HISTORY_33 = "medical_history_33";
    const MEDICAL_HISTORY_34 = "medical_history_34";
    const MEDICAL_HISTORY_35 = "medical_history_35";
    const MEDICAL_HISTORY_36 = "medical_history_36";
    const MEDICAL_HISTORY_37 = "medical_history_37";
    const MEDICAL_HISTORY_38 = "medical_history_38";
    const MEDICAL_HISTORY_39 = "medical_history_39";
    const MEDICAL_HISTORY_40 = "medical_history_40";
    const MEDICAL_HISTORY_41 = "medical_history_41";
    const MEDICAL_HISTORY_42 = "medical_history_42";
    const MEDICAL_HISTORY_43 = "medical_history_43";
    const MEDICAL_HISTORY_44 = "medical_history_44";
    const MEDICAL_HISTORY_45 = "medical_history_45";
    const MEDICAL_HISTORY_46 = "medical_history_46";
    const MEDICAL_HISTORY_47 = "medical_history_47";
    const MEDICAL_HISTORY_48 = "medical_history_48";
    const MEDICAL_HISTORY_49 = "medical_history_49";
    const MEDICAL_HISTORY_50 = "medical_history_50";
    const MEDICAL_HISTORY_51 = "medical_history_51";
    const MEDICAL_HISTORY_52 = "medical_history_52";
    const MEDICAL_HISTORY_53 = "medical_history_53";

    /**
     * {@inheritdoc}
     */
    public function load(ObjectManager $manager)
    {
        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_1, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('28 kg');
        $medicalHistory->setHeight('0.62 mts');
        $medicalHistory->setBloodType('0+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(0);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(0);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(1);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_2, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('28 kg');
        $medicalHistory->setHeight('0.62 mts');
        $medicalHistory->setBloodType('0+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(0);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(0);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(1);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_3, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('28 kg');
        $medicalHistory->setHeight('0.62 mts');
        $medicalHistory->setBloodType('0+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(0);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(0);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(1);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_4, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_5, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_6, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_7, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_8, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_9, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_10, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_11, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_12, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_13, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_14, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_15, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_16, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_17, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_18, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_19, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_20, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_21, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_22, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_23, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_24, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_25, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_26, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_27, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_28, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_29, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_30, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_31, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_32, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_33, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_34, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_35, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_36, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_37, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_38, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_39, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_40, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_41, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_42, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_43, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_44, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_45, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_46, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_47, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_48, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_49, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_50, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_51, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_52, $medicalHistory);

        $medicalHistory = new MedicalHistory();
        $medicalHistory->setWeight('25 kg');
        $medicalHistory->setHeight('0.58 mts');
        $medicalHistory->setBloodType('A+');
        $medicalHistory->setAllergy(null);
        $medicalHistory->setChronicIllness(null);
        $medicalHistory->setMedicine(null);
        $medicalHistory->setAsma(1);
        $medicalHistory->setSinusitis(0);
        $medicalHistory->setBronquitis(0);
        $medicalHistory->setOtitis(0);
        $medicalHistory->setTosConvulsiva(0);
        $medicalHistory->setMigrania(1);
        $medicalHistory->setDiabetes(0);
        $medicalHistory->setCeliaco(0);
        $manager->persist($medicalHistory);
        $this->addReference(self::MEDICAL_HISTORY_53, $medicalHistory);

        $manager->flush();
    }
}
